version: '3.8'

services:
  spring-boot-app:
    build:
      context: ./path/to/your/spring-boot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-cs1a94dds78s73b4p7mg-a.oregon-postgres.render.com:5432/library_a0lc
      SPRING_DATASOURCE_USERNAME: kent
      SPRING_DATASOURCE_PASSWORD: Jl4RdsMR3r8fius4Gpwr9yjLJw2FpvHo
    networks:
      - library-network
    restart: unless-stopped
    ports:
      - "8080:8080"

networks:
  library-network:
    driver: bridge